[package]
name = "thermite"
version = "0.1.0"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0.2"

[profile.release]
opt-level = 3
lto = 'fat'
codegen-units = 1